# -*- coding: utf-8 -*-
"""Python_Class02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QS12zs9t3JcGOVgd_e7h5HxJvz-h7LjJ

Table of 2
"""

for x in range(1, 11):
    print("2 x",x,"=",x*2)

"""Grade Define Table"""

# percentage = (percentage = *100)
percentage = float (input("Enter your percentage: "))
if  percentage >= 90:
    print("Grade A1+")
elif percentage >= 80:
    print("Grade A")
elif percentage >= 70:
    print("Grade B")
elif percentage >= 60:
    print("Grade C")
elif percentage >= 50:
    print("Grade D")
else:
    print("you are fail")