# -*- coding: utf-8 -*-
"""Python_Class01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIkwBTt4jpS_1Y4FHVrZsZrobFsbP2TO

# Arethmetic **Operators**
"""

7+5 == 12
55+64 == 119
print (7+5)
print (6*9)
6*7 == 42
print (10//7)
7+5 == 12
55+64 == 119

print (7+5)
print (6*9)
6*7 == 42
print (10//7)
print (11 // 5)

salman = 5
moin = 10

sum = salman + moin
print (sum, type(sum))

sub = salman - moin
print (sub, type(sub))

div = salman / moin
print (div, type(div))

floor_div = salman // moin
print (floor_div, type(floor_div))

mul = salman * moin
print (mul, type(mul))

mod = salman % moin
print (mod, type(mod))

exp = salman ** moin
print (exp, type(exp))

"""# Comparison **Operators**"""

Iphone = 7.5
Samsung = 5

print(Iphone == Samsung) # equal to
print(Iphone != Samsung) # not equal to
print(Iphone > Samsung) # greator then
print(Iphone < Samsung) # less then
print(Iphone >= Samsung) # greator then or equal to
print(Iphone <= Samsung) # less then or equal to

Iphone = 7.5
Samsung = 6

if Iphone == Samsung:
    print("Iphone is equal to Samsung")
else:
    print("Iphone is not equal to Samsung")

if Iphone != Samsung:
    print("Iphone is not equal to Samsung")
else:
    print("Iphone is equal to Samsung")

if Iphone > Samsung:
    print("Iphone is greator then Samsung")
else:
    print("Iphone is not greator then Samsung")

if Iphone < Samsung:
    print("Iphone is less then Samsung")
else:
    print("Iphone is not less then Samsung")

if Iphone >= Samsung:
    print("Iphone is greator then or equal to Samsung")
else:
    print("Iphone is not greator then or equal to Samsung")

if Iphone <= Samsung:
    print("Iphone is less then or equal to Samsung")
else:
    print("Iphone is not less then or equal to Samsung")

"""# Logical **operators**"""

nature = 5
wind = 20

print(nature > 0 and wind < 21 and nature >= wind) # all condition must be true then answer is true other wise false
print(nature > 0 or wind < 20) # one condition must be true then answer is true
print(not(nature > 8))   # positive input and nigetive answer as (vice of versa)

"""# Assigment **Operators**"""

x = 5

x += 10
print (x, type(x))

x = 8

x -= 1
print (x, type(x))

x = 11

x *= 4
print (x, type(x))

x = 6

x /= 2
print (x, type(x))

x = 5

x %= 3
print (x, type(x))

x = 9

x //= 2
print (x, type(x))

x = 14

x **= 1.2
print (x, type(x))